### ISSUE TITLE
Can this be built with the latest version of Android Studio?

### ISSUE THREAD

**Issue by funkyeah** [SiliconLabs/thunderboard-android#10]

**Comment by funkyeah** [comment]
Is anyone at the wheel?

**Comment by Egnima** [comment]
<img width="2032" alt="2018-08-10 6 55 09" src="https://user-images.githubusercontent.com/30615629/43951777-ecd585c6-9cce-11e8-8f3b-29b1f10e9f01.png">

**Comment by Egnima** [comment]
https://stackoverflow.com/questions/47152282/gradle-could-not-find-method-google-for-arguments-on-repository-container?noredirect=1&lq=1

**Comment by Egnima** [comment]
https://stackoverflow.com/questions/47152282/gradle-could-not-find-method-google-for-arguments-on-repository-container?noredirect=1&lq=1

**Comment by silabs-tiago** [comment]
Yes, you can use the latest Android Studio version.
