### ISSUE TITLE
Missing file DaggerActivityComponent

### ISSUE THREAD

**Issue by ggjersund** [SiliconLabs/thunderboard-android#12]
Can't find the following import
`import com.silabs.thunderboard.common.injection.component.DaggerActivityComponent;`
that is imported into DemosSelectionActivity and used in `ActivityComponent component()`.

Is this file essential?

**Comment by silabs-tiago** [comment]
Do you see the same thing with the latest version that was updated in November?

**Comment by ggjersund** [comment]
Hi @silabs-tiago, sorry for the late response, but I was not able to reproduce this, so I guess closing this issue is correct.

**Comment by ouhena** [comment]
Hello,

I have the same issue. I've tried to open the project in Android Studio 4.1.1, from both a zipped download and a SVN checkout, and it complains about 2 missing imports in DemoSelectionActivity.java:
`import com.silabs.thunderboard.BuildConfig;`
`import com.silabs.thunderboard.common.injection.component.DaggerActivityComponent;
`
