### ISSUE TITLE
pre-programmed firmware

### ISSUE THREAD

**Issue by JanKoci97** [SiliconLabs/thunderboard-android#15]
Hi all,

I would like to run Thunderboard application (https://play.google.com/store/apps/details?id=com.silabs.thunderboard) but I cannot find original program (pre-programmed firmware). Where can I download original program in binary format which I would just load to the microcontroller?

Thanks for your response.

**Comment by silabs-TiagoM** [comment]
Hi,

You need to install [Simplicity Studio 5](https://www.silabs.com/developers/simplicity-studio) and then install the Bluetooth SDK within that. When you connect your Thunderboard kit into the PC go to the Example Projects & Demos and you can flash the Thunderboard demo.

![image](https://user-images.githubusercontent.com/14230750/133072780-cdafe235-17cd-4b43-9004-5ef592f1765d.png)
