### ISSUE TITLE
Having Issue opening the app in Android Studio 2.1.2

### ISSUE THREAD

**Issue by mhdazeem** [SiliconLabs/thunderboard-android#2]
The error is 
"
repository not found
ext {
    // Open the Git repository in the current directory.
    grgit = org.ajoberstar.grgit.Grgit.open(dir: 'app.')
}"

**Comment by greghodgson** [comment]
Hi, the problem is possibly that the .git repo file is not found.  You may need to change the gradle.build file to read:

    grgit = org.ajoberstar.grgit.Grgit.open(dir: '.')

**Comment by mhdazeem** [comment]
I am still having the same issue this time its said cannot open the repository.

**Comment by snaikwade** [comment]
I am facing same issue.

ext {
    // Open the Git repository in the current directory.
    grgit = org.ajoberstar.grgit.Grgit.open(dir: '..')
}


I tried replacing '..' with '.' but it is not working
