### ISSUE TITLE
Repository Not Found

### ISSUE THREAD

**Issue by snaikwade** [SiliconLabs/thunderboard-android#4]
Getting error of repository not found

ext {
    // Open the Git repository in the current directory.
    grgit = org.ajoberstar.grgit.Grgit.open(dir: '..')
}

I tried replacing '..' with '.' as suggested in earlier issue thread but problem still persists

**Comment by sparrowapps** [comment]
do not download zip

open in desktop
open project with Android studio 2.x

grgit = org.ajoberstar.grgit.Grgit.open(dir: '..')
-->
grgit = org.ajoberstar.grgit.Grgit.open(dir: '.')

build ok

**Comment by RachelBaksht** [comment]
ן opened  desktop 
but i do't see this project

**Comment by srikapardhi** [comment]
The firebase repository not found.

**Comment by silabs-tiago** [comment]
Cloud streaming has been temporarily disabled from the app.
