### ISSUE TITLE
Cannot connect on LG G4

### ISSUE THREAD

**Issue by steho** [SiliconLabs/thunderboard-android#6]
Hello,
the app does not work on my LG G4. It hardly recognizes the Thunderboard 2 (mostly only once after a forced restart) and when it does it either is "Unable to connect" or it cannot read the sensors but looses the connection again.
I tried it on a Medion tablett, there it works as expected.
Kind regards
Stephan

**Comment by silabs-tiago** [comment]
The scanning issues have been fixed in the latest app version available on the playstore.
