### ISSUE TITLE
Cannot set the value of read-only property 'outputFile' 

### ISSUE THREAD

**Issue by migmeltw** [SiliconLabs/thunderboard-android#8]
Hello, anybody know how to deal with this error message :
2/21/2018
4:24 PM	Gradle sync started

4:25 PM	Gradle sync failed: Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.
				Consult IDE log for more details (Help | Show Log) (19s 915ms)

**Comment by silabs-tiago** [comment]
Do you have the same error with the latest version?
